[general]
excluded_routes=192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
geo_location_checker=https://raw.githubusercontent.com/thuhollow2/qure/main/Other/IP_API.js
network_check_url=http://www.baidu.com/
server_check_url=http://www.gstatic.com/generate_204

[dns]
server=119.29.29.29
server=223.5.5.5
server=1.0.0.1
server=8.8.8.8

[policy]
static=🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 🎥 流媒体解锁, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
url-latency-benchmark=♻️ 自动选择, 本文件创建时间：Mon May 15 00:27:26 UTC 2023, 🇦🇷AR-131.255.7.39-8081, 🇫🇷FR-15.188.74.219-8181, 🇮🇳IN-152.70.74.66-443, 🇯🇵JP-18.179.52.115-28785, 🇺🇸US-209.141.60.31-43500, 🇸🇬SG-13.215.177.20-443, 🇺🇸US-135.148.149.209-80, 🇸🇬SG-13.215.194.103-443, 🇸🇬SG-13.215.252.181-443, 🇸🇬SG-13.215.159.48-443, 🇺🇸US-137.175.6.6-443, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 手动切换-1, 本文件创建时间：Mon May 15 00:27:26 UTC 2023, 🇦🇷AR-131.255.7.39-8081, 🇫🇷FR-15.188.74.219-8181, 🇮🇳IN-152.70.74.66-443, 🇯🇵JP-18.179.52.115-28785, 🇺🇸US-209.141.60.31-43500, 🇸🇬SG-13.215.177.20-443, 🇺🇸US-135.148.149.209-80, 🇸🇬SG-13.215.194.103-443, 🇸🇬SG-13.215.252.181-443, 🇸🇬SG-13.215.159.48-443, 🇺🇸US-137.175.6.6-443
static=🚀 手动切换-2, 本文件创建时间：Mon May 15 00:27:26 UTC 2023, 🇦🇷AR-131.255.7.39-8081, 🇫🇷FR-15.188.74.219-8181, 🇮🇳IN-152.70.74.66-443, 🇯🇵JP-18.179.52.115-28785, 🇺🇸US-209.141.60.31-43500, 🇸🇬SG-13.215.177.20-443, 🇺🇸US-135.148.149.209-80, 🇸🇬SG-13.215.194.103-443, 🇸🇬SG-13.215.252.181-443, 🇸🇬SG-13.215.159.48-443, 🇺🇸US-137.175.6.6-443
static=♻️ IPv6-自动, 🇺🇸US-135.148.149.209-80, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 IPv6-手动, 🇺🇸US-135.148.149.209-80, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=🛑 广告拦截, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Advertising.png
static=📢 ChatGPT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Star.png
static=📢 Bard, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, 🇺🇸 美国节点, 🇬🇧 英国节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Star.png
static=Ⓜ️ NewBing, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Microsoft.png
static=Ⓜ️ 微软服务, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Microsoft.png
static=🍎 苹果服务, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Apple.png
static=🎮 国际游戏, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Game.png
static=🌍 国外媒体, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 🎥 流媒体解锁, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Media.png
static=🌏 国内媒体, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Media.png
static=🎯 国内网站, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Direct.png
static=🐟 其他网站, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Final.png
static=🎥 流媒体解锁, direct, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Unlock.png
static=👍 高级节点, direct, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/VIP.png
static=📺 省流节点, direct
static=🇨🇳 大陆节点, direct
static=🇭🇰 香港节点, direct
static=🇲🇴 澳门节点, direct
static=🇹🇼 台湾节点, direct
url-latency-benchmark=🇸🇬 新加坡节点, 🇸🇬SG-13.215.177.20-443, 🇸🇬SG-13.215.194.103-443, 🇸🇬SG-13.215.252.181-443, 🇸🇬SG-13.215.159.48-443
static=🇯🇵 日本节点, 🇯🇵JP-18.179.52.115-28785
static=🇰🇷 韩国节点, direct
static=🇲🇾 马来西亚节点, direct
static=🇹🇭 泰国节点, direct
static=🇻🇳 越南节点, direct
static=🇰🇭 柬埔寨节点, direct
static=🇮🇩 印度尼西亚节点, direct
static=🇵🇭 菲律宾节点, direct
static=🇲🇳 蒙古节点, direct
static=🇮🇷 伊朗节点, direct
static=🇮🇳 印度节点, 🇮🇳IN-152.70.74.66-443
static=🇹🇷 土耳其节点, direct
static=🇮🇱 以色列节点, direct
static=🇸🇦 沙特阿拉伯节点, direct
static=🇦🇺 澳大利亚节点, direct
static=🇳🇿 新西兰节点, direct
static=🇨🇦 加拿大节点, direct
static=🇲🇽 墨西哥节点, direct
static=🇵🇦 巴拿马节点, direct
static=🇷🇺 俄罗斯节点, direct
static=🇺🇦 乌克兰节点, direct
url-latency-benchmark=🇺🇸 美国节点, 🇺🇸US-209.141.60.31-43500, 🇺🇸US-135.148.149.209-80, 🇺🇸US-137.175.6.6-443
static=🇬🇧 英国节点, direct
static=🇫🇷 法国节点, 🇫🇷FR-15.188.74.219-8181
static=🇩🇪 德国节点, direct
static=🇵🇱 波兰节点, direct
static=🇩🇰 丹麦节点, direct
static=🇳🇴 挪威节点, direct
static=🇸🇪 瑞典节点, direct
static=🇫🇮 芬兰节点, direct
static=🇮🇸 冰岛节点, direct
static=🇨🇿 捷克节点, direct
static=🇨🇭 瑞士节点, direct
static=🇬🇷 希腊节点, direct
static=🇳🇱 荷兰节点, direct
static=🇮🇹 意大利节点, direct
static=🇱🇹 立陶宛节点, direct
static=🇪🇸 西班牙节点, direct
static=🇵🇹 葡萄牙节点, direct
static=🇧🇷 巴西节点, direct
static=🇨🇱 智利节点, direct
static=🇵🇪 秘鲁节点, direct
static=🇦🇷 阿根廷节点, 🇦🇷AR-131.255.7.39-8081
static=🇪🇬 埃及节点, direct
static=🇿🇦 南非节点, direct

[server_remote]

[filter_remote]
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/BanAD.list, tag=🛑 广告拦截, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/BanProgramAD.list, tag=🛑 广告拦截, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Bing.list, tag=Ⓜ️ NewBing, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Microsoft.list, tag=Ⓜ️ 微软服务, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Apple.list, tag=🍎 苹果服务, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Game.list, tag=🎮 国际游戏, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ProxyMedia.list, tag=🌍 国外媒体, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaMedia.list, tag=🌏 国内媒体, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ProxyGFWlist.list, tag=🚀 节点选择, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/LocalAreaNetwork.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/UnBan.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaDomain.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaCompanyIp.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaIp.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/GoogleCN.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/SteamCN.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Download.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Direct.list, tag=🎯 国内网站, enabled=true

[rewrite_remote]

[server_local]
vmess = 255.255.255.255:10086, method=chacha20-ietf-poly1305, password=00000000-0000-0000-0000-000000000000, aead=true, fast-open=false, udp-relay=true, tag=本文件创建时间：Mon May 15 00:27:26 UTC 2023
shadowsocks = us-am3.eqnode.net:8081, method=aes-256-cfb, password=fou8MBGij, ssr-protocol=origin, obfs=tls1.2_ticket_auth, fast-open=false, udp-relay=true, tag=🇦🇷AR-131.255.7.39-8081
shadowsocks = fr-am1-5.eqsunshine.com:8181, method=aes-256-cfb, password=RcfVcDzzB, ssr-protocol=origin, obfs=tls1.2_ticket_auth, fast-open=false, udp-relay=true, tag=🇫🇷FR-15.188.74.219-8181
trojan = 152.70.74.66:443, password=d906afe5-7c3c-4ddc-aaa4-61c154a82e5e, over-tls=false, fast-open=false, udp-relay=true, tag=🇮🇳IN-152.70.74.66-443
vmess = jp06-vm0.entry.jpojpoh.art:28785, method=chacha20-ietf-poly1305, password=22acc467-7440-386a-927a-d84be554b37e, aead=false, tls13=false, obfs=over-tls, obfs-host=jp06-vm0.entry.jpojpoh.art, fast-open=false, udp-relay=true, tls-verification=false, tag=🇯🇵JP-18.179.52.115-28785
trojan = streaming.teacher2040.com:43500, password=D44B7434-927C-AE52-D51F-A790C19ED74A, over-tls=true, tls-host=, tls13=false, fast-open=false, udp-relay=true, tls-verification=false, tag=🇺🇸US-209.141.60.31-43500
trojan = 13.215.177.20:443, password=794d739c-89a0-444c-b2e7-acce12af3042, over-tls=true, tls-host=data.amazon-azure.com, tls13=false, fast-open=false, udp-relay=true, tls-verification=false, tag=🇸🇬SG-13.215.177.20-443
trojan = us2.trojanvh.xyz:80, password=011eb011-c68e-4f92-80eb-f9bbef707bef, over-tls=true, tls-host=, tls13=false, fast-open=false, udp-relay=true, tls-verification=false, tag=🇺🇸US-135.148.149.209-80
trojan = 13.215.194.103:443, password=4aeda200-44c9-4168-8f2a-a00a72176d35, over-tls=true, tls-host=data.amazon-azure.com, tls13=false, fast-open=false, udp-relay=true, tls-verification=false, tag=🇸🇬SG-13.215.194.103-443
trojan = awssg18-data.amazon-azure.com:443, password=4aeda200-44c9-4168-8f2a-a00a72176d35, over-tls=true, tls-host=data.amazon-azure.com, tls13=false, fast-open=false, udp-relay=true, tls-verification=false, tag=🇸🇬SG-13.215.252.181-443
trojan = awssg16-data.amazon-azure.com:443, password=4aeda200-44c9-4168-8f2a-a00a72176d35, over-tls=true, tls-host=data.amazon-azure.com, tls13=false, fast-open=false, udp-relay=true, tls-verification=false, tag=🇸🇬SG-13.215.159.48-443
vmess = 23.227.38.99:443, method=chacha20-ietf-poly1305, password=86d37526-5758-4cec-862f-df404b313086, aead=true, tls13=false, obfs=wss, obfs-host=1.freek1.xyz, obfs-uri=/3G6WPDL7, fast-open=false, udp-relay=true, tls-verification=false, tag=🇺🇸US-137.175.6.6-443

[filter_local]
DOMAIN-SUFFIX,openai.com,📢 ChatGPT
DOMAIN-SUFFIX,challenges.cloudflare.com,📢 ChatGPT
DOMAIN-SUFFIX,ai.com,📢 ChatGPT
DOMAIN-SUFFIX,bard.google.com,📢 Bard
GEOIP,CN,🎯 国内网站,no-resolve
FINAL,🐟 其他网站

[rewrite_local]

[mitm]

