[general]
excluded_routes=192.168.0.0/16, 172.16.0.0/12, 100.64.0.0/10, 10.0.0.0/8
geo_location_checker=https://raw.githubusercontent.com/thuhollow2/qure/main/Other/IP_API.js
network_check_url=http://www.baidu.com/
server_check_url=http://www.gstatic.com/generate_204

[dns]
server=119.29.29.29
server=223.5.5.5
server=1.0.0.1
server=8.8.8.8

[policy]
static=🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 🎥 流媒体解锁, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
url-latency-benchmark=♻️ 自动选择, 本文件创建时间：Tue May 16 00:29:46 UTC 2023, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.134.16.190-11023, 🇨🇳CN-47.93.231.218-53022, 🇪🇬EG-41.215.242.178-989, 🇮🇪IE-23.92.127.133-989, 🇵🇱PL-217.182.76.202-80, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 手动切换-1, 本文件创建时间：Tue May 16 00:29:46 UTC 2023, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.134.16.190-11023, 🇨🇳CN-47.93.231.218-53022, 🇪🇬EG-41.215.242.178-989, 🇮🇪IE-23.92.127.133-989, 🇵🇱PL-217.182.76.202-80
static=🚀 手动切换-2, 本文件创建时间：Tue May 16 00:29:46 UTC 2023, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.134.16.190-11023, 🇨🇳CN-47.93.231.218-53022, 🇪🇬EG-41.215.242.178-989, 🇮🇪IE-23.92.127.133-989, 🇵🇱PL-217.182.76.202-80
static=♻️ IPv6-自动, DIRECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Auto.png
static=🚀 IPv6-手动, DIRECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Proxy.png
static=🛑 广告拦截, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Advertising.png
static=📢 ChatGPT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Star.png
static=📢 Bard, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, 🇺🇸 美国节点, 🇬🇧 英国节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Star.png
static=Ⓜ️ NewBing, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Microsoft.png
static=Ⓜ️ 微软服务, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Microsoft.png
static=🍎 苹果服务, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Apple.png
static=🎮 国际游戏, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Game.png
static=🌍 国外媒体, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 🎥 流媒体解锁, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, DIRECT, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Media.png
static=🌏 国内媒体, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Media.png
static=🎯 国内网站, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Direct.png
static=🐟 其他网站, DIRECT, 🚀 节点选择, ♻️ 自动选择, 🚀 手动切换-1, 🚀 手动切换-2, ♻️ IPv6-自动, 🚀 IPv6-手动, 👍 高级节点, 📺 省流节点, 🇨🇳 大陆节点, 🇭🇰 香港节点, 🇲🇴 澳门节点, 🇹🇼 台湾节点, 🇸🇬 新加坡节点, 🇯🇵 日本节点, 🇰🇷 韩国节点, 🇲🇾 马来西亚节点, 🇹🇭 泰国节点, 🇻🇳 越南节点, 🇰🇭 柬埔寨节点, 🇮🇩 印度尼西亚节点, 🇵🇭 菲律宾节点, 🇲🇳 蒙古节点, 🇮🇷 伊朗节点, 🇮🇳 印度节点, 🇹🇷 土耳其节点, 🇮🇱 以色列节点, 🇸🇦 沙特阿拉伯节点, 🇦🇺 澳大利亚节点, 🇳🇿 新西兰节点, 🇨🇦 加拿大节点, 🇲🇽 墨西哥节点, 🇵🇦 巴拿马节点, 🇷🇺 俄罗斯节点, 🇺🇦 乌克兰节点, 🇺🇸 美国节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇵🇱 波兰节点, 🇩🇰 丹麦节点, 🇳🇴 挪威节点, 🇸🇪 瑞典节点, 🇫🇮 芬兰节点, 🇮🇸 冰岛节点, 🇨🇿 捷克节点, 🇨🇭 瑞士节点, 🇬🇷 希腊节点, 🇳🇱 荷兰节点, 🇮🇹 意大利节点, 🇱🇹 立陶宛节点, 🇪🇸 西班牙节点, 🇵🇹 葡萄牙节点, 🇧🇷 巴西节点, 🇨🇱 智利节点, 🇵🇪 秘鲁节点, 🇦🇷 阿根廷节点, 🇪🇬 埃及节点, 🇿🇦 南非节点, REJECT, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Final.png
static=🎥 流媒体解锁, direct, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/Unlock.png
static=👍 高级节点, direct, img-url=https://raw.githubusercontent.com/thuhollow2/qure/main/IconSet/Color/VIP.png
static=📺 省流节点, direct
url-latency-benchmark=🇨🇳 大陆节点, 🇨🇳CN-123.249.101.15-19709, 🇨🇳CN-36.134.16.190-11023, 🇨🇳CN-47.93.231.218-53022
static=🇭🇰 香港节点, direct
static=🇲🇴 澳门节点, direct
static=🇹🇼 台湾节点, direct
static=🇸🇬 新加坡节点, direct
static=🇯🇵 日本节点, direct
static=🇰🇷 韩国节点, direct
static=🇲🇾 马来西亚节点, direct
static=🇹🇭 泰国节点, direct
static=🇻🇳 越南节点, direct
static=🇰🇭 柬埔寨节点, direct
static=🇮🇩 印度尼西亚节点, direct
static=🇵🇭 菲律宾节点, direct
static=🇲🇳 蒙古节点, direct
static=🇮🇷 伊朗节点, direct
static=🇮🇳 印度节点, direct
static=🇹🇷 土耳其节点, direct
static=🇮🇱 以色列节点, direct
static=🇸🇦 沙特阿拉伯节点, direct
static=🇦🇺 澳大利亚节点, direct
static=🇳🇿 新西兰节点, direct
static=🇨🇦 加拿大节点, direct
static=🇲🇽 墨西哥节点, direct
static=🇵🇦 巴拿马节点, direct
static=🇷🇺 俄罗斯节点, direct
static=🇺🇦 乌克兰节点, direct
static=🇺🇸 美国节点, direct
static=🇬🇧 英国节点, direct
static=🇫🇷 法国节点, direct
static=🇩🇪 德国节点, direct
static=🇵🇱 波兰节点, 🇵🇱PL-217.182.76.202-80
static=🇩🇰 丹麦节点, direct
static=🇳🇴 挪威节点, direct
static=🇸🇪 瑞典节点, direct
static=🇫🇮 芬兰节点, direct
static=🇮🇸 冰岛节点, direct
static=🇨🇿 捷克节点, direct
static=🇨🇭 瑞士节点, direct
static=🇬🇷 希腊节点, direct
static=🇳🇱 荷兰节点, direct
static=🇮🇹 意大利节点, direct
static=🇱🇹 立陶宛节点, direct
static=🇪🇸 西班牙节点, direct
static=🇵🇹 葡萄牙节点, direct
static=🇧🇷 巴西节点, direct
static=🇨🇱 智利节点, direct
static=🇵🇪 秘鲁节点, direct
static=🇦🇷 阿根廷节点, direct
static=🇪🇬 埃及节点, 🇪🇬EG-41.215.242.178-989
static=🇿🇦 南非节点, direct

[server_remote]

[filter_remote]
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/BanAD.list, tag=🛑 广告拦截, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/BanProgramAD.list, tag=🛑 广告拦截, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Bing.list, tag=Ⓜ️ NewBing, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Microsoft.list, tag=Ⓜ️ 微软服务, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Apple.list, tag=🍎 苹果服务, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Game.list, tag=🎮 国际游戏, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ProxyMedia.list, tag=🌍 国外媒体, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaMedia.list, tag=🌏 国内媒体, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ProxyGFWlist.list, tag=🚀 节点选择, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/LocalAreaNetwork.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/UnBan.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaDomain.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaCompanyIp.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/ChinaIp.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/GoogleCN.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/SteamCN.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Download.list, tag=🎯 国内网站, enabled=true
https://raw.githubusercontent.com/thuhollow2/rule/main/QuantumultX/Direct.list, tag=🎯 国内网站, enabled=true

[rewrite_remote]

[server_local]
vmess = 255.255.255.255:10086, method=chacha20-ietf-poly1305, password=00000000-0000-0000-0000-000000000000, aead=true, fast-open=false, udp-relay=true, tag=本文件创建时间：Tue May 16 00:29:46 UTC 2023
vmess = 123.249.101.15:19709, method=chacha20-ietf-poly1305, password=2f278a45-940a-46c1-c886-77f3b2d33987, aead=true, obfs=ws, obfs-host=, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-123.249.101.15-19709
vmess = 36.134.16.190:11023, method=chacha20-ietf-poly1305, password=8c042a38-71c1-1dcb-00df-54880236e0dc, aead=true, fast-open=false, udp-relay=true, tag=🇨🇳CN-36.134.16.190-11023
vmess = 47.93.231.218:53022, method=chacha20-ietf-poly1305, password=95fd7642-2160-4528-e909-3d526b533013, aead=true, obfs=ws, obfs-host=, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇨🇳CN-47.93.231.218-53022
shadowsocks = 41.215.242.180:989, method=aes-256-cfb, password=f8f7aCzcPKbsF8p3, fast-open=false, udp-relay=true, tag=🇪🇬EG-41.215.242.178-989
shadowsocks = 23.92.127.134:989, method=aes-256-cfb, password=f8f7aCzcPKbsF8p3, fast-open=false, udp-relay=true, tag=🇮🇪IE-23.92.127.133-989
vmess = pl2-vmess.greenssh.xyz:80, method=chacha20-ietf-poly1305, password=7487c25a-e899-44d8-9d71-8b9ab4ff5d26, aead=true, obfs=ws, obfs-host=pl2-vmess.greenssh.xyz, obfs-uri=/, fast-open=false, udp-relay=true, tag=🇵🇱PL-217.182.76.202-80

[filter_local]
DOMAIN-SUFFIX,openai.com,📢 ChatGPT
DOMAIN-SUFFIX,challenges.cloudflare.com,📢 ChatGPT
DOMAIN-SUFFIX,ai.com,📢 ChatGPT
DOMAIN-SUFFIX,bard.google.com,📢 Bard
GEOIP,CN,🎯 国内网站,no-resolve
FINAL,🐟 其他网站

[rewrite_local]

[mitm]

