[General]
allow-udp-proxy=false
bypass-tun=10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server=system,119.29.29.29,223.5.5.5
host=127.0.0.1
skip-proxy=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com

[Proxy]
本文件创建时间：Sun May 14 00:30:14 UTC 2023 = vmess,255.255.255.255,10086,chacha20-ietf-poly1305,"00000000-0000-0000-0000-000000000000",over-tls:false,transport:tcp,skip-cert-verify:1
🇨🇳CN-112.132.215.189-50002 = vmess,112.132.215.189,50002,chacha20-ietf-poly1305,"418048af-a293-4b99-9b0c-98ca3580dd24",over-tls:false,transport:tcp,skip-cert-verify:1
🇨🇳CN-123.249.101.15-19709 = vmess,123.249.101.15,19709,chacha20-ietf-poly1305,"2f278a45-940a-46c1-c886-77f3b2d33987",over-tls:false,transport:ws,path:/,host:,skip-cert-verify:1
🇫🇮FI-37.143.129.230-989 = Shadowsocks,37.143.129.230,989,aes-256-cfb,"f8f7aCzcPKbsF8p3"
🇯🇵JP-43.207.109.56-443 = Shadowsocks,43.207.109.56,443,aes-256-cfb,"amazonskr05"
🇯🇵JP-43.207.199.196-443 = Shadowsocks,43.207.199.196,443,aes-256-cfb,"amazonskr05"
🇰🇷KR-43.201.6.53-443 = Shadowsocks,43.201.6.53,443,aes-256-cfb,"amazonskr05"
🇺🇸US-142.0.141.113-53452 = vmess,142.0.130.8,53452,chacha20-ietf-poly1305,"418048af-a293-4b99-9b0c-98ca3580dd24",over-tls:false,transport:tcp,skip-cert-verify:1
🇺🇸US-216.52.183.242-80 = Shadowsocks,216.52.183.242,80,aes-128-gcm,"83XvX4Vo%*3a",http

[Remote Proxy]

[Proxy Group]
🚀 节点选择 = select,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,🎥 流媒体解锁,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,DIRECT,REJECT
♻️ 自动选择 = url-test,本文件创建时间：Sun May 14 00:30:14 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-123.249.101.15-19709,🇫🇮FI-37.143.129.230-989,🇯🇵JP-43.207.109.56-443,🇯🇵JP-43.207.199.196-443,🇰🇷KR-43.201.6.53-443,🇺🇸US-142.0.141.113-53452,🇺🇸US-216.52.183.242-80,url=http://www.gstatic.com/generate_204,interval=300
🚀 手动切换-1 = select,本文件创建时间：Sun May 14 00:30:14 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-123.249.101.15-19709,🇫🇮FI-37.143.129.230-989,🇯🇵JP-43.207.109.56-443,🇯🇵JP-43.207.199.196-443,🇰🇷KR-43.201.6.53-443,🇺🇸US-142.0.141.113-53452,🇺🇸US-216.52.183.242-80
🚀 手动切换-2 = select,本文件创建时间：Sun May 14 00:30:14 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-123.249.101.15-19709,🇫🇮FI-37.143.129.230-989,🇯🇵JP-43.207.109.56-443,🇯🇵JP-43.207.199.196-443,🇰🇷KR-43.201.6.53-443,🇺🇸US-142.0.141.113-53452,🇺🇸US-216.52.183.242-80
🛑 广告拦截 = select,DIRECT,REJECT
📢 ChatGPT = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,DIRECT,REJECT
📢 Bard = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,🇺🇸 美国节点,🇬🇧 英国节点,DIRECT,REJECT
Ⓜ️ NewBing = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,DIRECT,REJECT
Ⓜ️ 微软服务 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🍎 苹果服务 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🎮 国际游戏 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🌍 国外媒体 = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,🎥 流媒体解锁,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,DIRECT,REJECT
🌏 国内媒体 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🎯 国内网站 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🐟 其他网站 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🎥 流媒体解锁 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
👍 高级节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
📺 省流节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇨🇳 大陆节点 = url-test,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-123.249.101.15-19709,url=http://www.gstatic.com/generate_204,interval=300
🇭🇰 香港节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇲🇴 澳门节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇹🇼 台湾节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇸🇬 新加坡节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇯🇵 日本节点 = url-test,🇯🇵JP-43.207.109.56-443,🇯🇵JP-43.207.199.196-443,url=http://www.gstatic.com/generate_204,interval=300
🇰🇷 韩国节点 = url-test,🇰🇷KR-43.201.6.53-443,url=http://www.gstatic.com/generate_204,interval=300
🇲🇾 马来西亚节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇹🇭 泰国节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇻🇳 越南节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇰🇭 柬埔寨节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇮🇩 印度尼西亚节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇵🇭 菲律宾节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇲🇳 蒙古节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇮🇷 伊朗节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇮🇳 印度节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇹🇷 土耳其节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇮🇱 以色列节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇸🇦 沙特阿拉伯节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇦🇺 澳大利亚节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇳🇿 新西兰节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇨🇦 加拿大节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇲🇽 墨西哥节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇵🇦 巴拿马节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇷🇺 俄罗斯节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇺🇦 乌克兰节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇺🇸 美国节点 = url-test,🇺🇸US-142.0.141.113-53452,🇺🇸US-216.52.183.242-80,url=http://www.gstatic.com/generate_204,interval=300
🇬🇧 英国节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇫🇷 法国节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇩🇪 德国节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇵🇱 波兰节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇩🇰 丹麦节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇳🇴 挪威节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇸🇪 瑞典节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇫🇮 芬兰节点 = url-test,🇫🇮FI-37.143.129.230-989,url=http://www.gstatic.com/generate_204,interval=300
🇮🇸 冰岛节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇨🇿 捷克节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇨🇭 瑞士节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇬🇷 希腊节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇳🇱 荷兰节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇮🇹 意大利节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇱🇹 立陶宛节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇪🇸 西班牙节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇵🇹 葡萄牙节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇧🇷 巴西节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇨🇱 智利节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇵🇪 秘鲁节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇦🇷 阿根廷节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇪🇬 埃及节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300
🇿🇦 南非节点 = url-test,DIRECT,url=http://www.gstatic.com/generate_204,interval=300

[Rule]
DOMAIN-SUFFIX,openai.com,📢 ChatGPT
DOMAIN-SUFFIX,challenges.cloudflare.com,📢 ChatGPT
DOMAIN-SUFFIX,ai.com,📢 ChatGPT
DOMAIN-SUFFIX,bard.google.com,📢 Bard
GEOIP,CN,🎯 国内网站,no-resolve
FINAL,🐟 其他网站

[Remote Rule]
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanAD.list,🛑 广告拦截
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanProgramAD.list,🛑 广告拦截
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Bing.list,Ⓜ️ NewBing
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Microsoft.list,Ⓜ️ 微软服务
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Apple.list,🍎 苹果服务
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Game.list,🎮 国际游戏
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ProxyMedia.list,🌍 国外媒体
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaMedia.list,🌏 国内媒体
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ProxyGFWlist.list,🚀 节点选择
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/LocalAreaNetwork.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/UnBan.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaDomain.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaCompanyIp.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaIp.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/GoogleCN.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/SteamCN.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Download.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Direct.list,🎯 国内网站

[URL Rewrite]
enable=true
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302

[Remote Rewrite]
https://raw.githubusercontent.com/thuhollow2/rule/main/Loon/AutoRewrite_Example.list,auto

[MITM]
enable=true
hostname=*.example.com,*.sample.com
skip-server-cert-verify=true

