[General]
allow-udp-proxy=false
bypass-tun=10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server=system,119.29.29.29,223.5.5.5
host=127.0.0.1
skip-proxy=192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com

[Proxy]
本文件创建时间：Sun Apr 30 08:32:42 UTC 2023 = vmess,255.255.255.255,10086,chacha20-ietf-poly1305,"00000000-0000-0000-0000-000000000000",over-tls:false,transport:tcp,skip-cert-verify:1
Relay_🇺🇸US-🇺🇸US_1650 = vmess,hk4.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"a316207e-0d3b-4754-ae9f-a4ec13aacba9",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
Relay_🇺🇸US-🇺🇸US_1652 = vmess,hk2.c2bfe79372be.sanfen004.me,443,chacha20-ietf-poly1305,"30ba67cf-776c-48be-8bb5-578878830228",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
Relay_🇺🇸US-🇺🇸US_1646 = vmess,hk2.c2bfe79372be.sanfen004.me,443,chacha20-ietf-poly1305,"a316207e-0d3b-4754-ae9f-a4ec13aacba9",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
美国_0430561 = vmess,170.114.45.224,2053,chacha20-ietf-poly1305,"eb049927-50cf-4fb6-a30f-ce8b6f256dbd",over-tls:true,tls-name:one.nikannetwork.xyz,transport:ws,path:/,host:one.nikannetwork.xyz,skip-cert-verify:1
Relay_🇺🇸US-🇺🇸US_1649 = vmess,hk4.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"30ba67cf-776c-48be-8bb5-578878830228",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
Relay_🇺🇸US-🇺🇸US_1647 = vmess,hk5.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"30ba67cf-776c-48be-8bb5-578878830228",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
Relay_🇺🇸US-🇺🇸US_1653 = vmess,hk5.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"a316207e-0d3b-4754-ae9f-a4ec13aacba9",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
🇭🇰_HK_香港_1_0@7 = vmess,hk3.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"a316207e-0d3b-4754-ae9f-a4ec13aacba9",over-tls:true,tls-name:hk3.af49c4e4c2ef.sanfen004.me,transport:ws,path:/zh-cn,host:hk3.af49c4e4c2ef.sanfen004.me,skip-cert-verify:1
Relay_🇺🇸US-🇺🇸US_1648 = vmess,hk3.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"a316207e-0d3b-4754-ae9f-a4ec13aacba9",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
Relay_🇦🇺AU-🇦🇺AU_23 = vmess,hk6.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"29387883-aace-4e03-bad7-940bc5e6ba67",over-tls:true,tls-name:hk6.af49c4e4c2ef.sanfen004.me,transport:ws,path:/zh-cn,host:hk6.af49c4e4c2ef.sanfen004.me,skip-cert-verify:1
德国_0430030 = vmess,85.208.107.119,38183,chacha20-ietf-poly1305,"6b32d610-1e0c-45b0-e91d-af12ccaeed8b",over-tls:false,transport:ws,path:/,host:85.208.107.119,skip-cert-verify:1
🇵🇦_PA_巴拿马_24@1 = vmess,185.143.220.25,443,chacha20-ietf-poly1305,"f28e354e-c2d1-4983-9b07-5acaf1b3b3e5",over-tls:true,tls-name:,transport:ws,path:/6e9EtZ2dL,host:,skip-cert-verify:1
Relay_🇦🇺AU-🇦🇺AU_1134 = vmess,hk6.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"30ba67cf-776c-48be-8bb5-578878830228",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
Relay_🇺🇸US-🇺🇸US_1651 = vmess,hk3.af49c4e4c2ef.sanfen004.me,443,chacha20-ietf-poly1305,"30ba67cf-776c-48be-8bb5-578878830228",over-tls:true,tls-name:www.microsoft.com,transport:ws,path:/zh-cn,host:www.microsoft.com,skip-cert-verify:1
德国_0430031 = vmess,51.75.74.253,10000,chacha20-ietf-poly1305,"df05adba-e5fb-11ed-a1bd-5fee106af88d",over-tls:false,transport:ws,path:/vpnjantit,host:51.75.74.253,skip-cert-verify:1
🇯🇵JP-54.178.9.238-15352 = trojan,jp2.gsjc.cfd,443,362a7af3-9ef9-4a6a-914b-5f85bfb1ef9f,tls-name:20-212-60-88.nhost.00cdn.com,skip-cert-verify:1
🇯🇵JP-43.207.100.84-1066 = trojan,awsjp6-data.amazon-azure.com,443,6d6b76a0-7be8-4935-a284-77d000401d3a,tls-name:data.amazon-azure.com,skip-cert-verify:1
🇮🇳_IN_印度_0@6 = vmess,27.124.20.240,44002,chacha20-ietf-poly1305,"418048af-a293-4b99-9b0c-98ca3580dd24",over-tls:false,transport:tcp,skip-cert-verify:1
_21 = trojan,195.15.243.26,443,4478,skip-cert-verify:1
未知_04302657 = vmess,Kansas.kotick.site,443,chacha20-ietf-poly1305,"2F094845-E2BD-EBF7-DEB7-995992436FAF",over-tls:true,tls-name:Kansas.kotick.site,transport:ws,path:/speedtest,host:Kansas.kotick.site,skip-cert-verify:1

[Remote Proxy]

[Proxy Group]
🚀 节点选择 = select,♻️ 自动选择,♻️ IPv6,🚀 手动切换-1,🚀 手动切换-2,🎥 流媒体解锁,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,DIRECT,REJECT
♻️ 自动选择 = url-test,本文件创建时间：Sun Apr 30 08:32:42 UTC 2023,Relay_🇺🇸US-🇺🇸US_1650,Relay_🇺🇸US-🇺🇸US_1652,Relay_🇺🇸US-🇺🇸US_1646,美国_0430561,Relay_🇺🇸US-🇺🇸US_1649,Relay_🇺🇸US-🇺🇸US_1647,Relay_🇺🇸US-🇺🇸US_1653,🇭🇰_HK_香港_1_0@7,Relay_🇺🇸US-🇺🇸US_1648,Relay_🇦🇺AU-🇦🇺AU_23,德国_0430030,🇵🇦_PA_巴拿马_24@1,Relay_🇦🇺AU-🇦🇺AU_1134,Relay_🇺🇸US-🇺🇸US_1651,德国_0430031,🇯🇵JP-54.178.9.238-15352,🇯🇵JP-43.207.100.84-1066,🇮🇳_IN_印度_0@6,_21,未知_04302657,url=https://www.google.com/generate_204,interval=300
♻️ IPv6 = url-test,🇵🇦_PA_巴拿马_24@1,_21,url=https://www.google.com/generate_204,interval=300
🚀 手动切换-1 = select,本文件创建时间：Sun Apr 30 08:32:42 UTC 2023,Relay_🇺🇸US-🇺🇸US_1650,Relay_🇺🇸US-🇺🇸US_1652,Relay_🇺🇸US-🇺🇸US_1646,美国_0430561,Relay_🇺🇸US-🇺🇸US_1649,Relay_🇺🇸US-🇺🇸US_1647,Relay_🇺🇸US-🇺🇸US_1653,🇭🇰_HK_香港_1_0@7,Relay_🇺🇸US-🇺🇸US_1648,Relay_🇦🇺AU-🇦🇺AU_23,德国_0430030,🇵🇦_PA_巴拿马_24@1,Relay_🇦🇺AU-🇦🇺AU_1134,Relay_🇺🇸US-🇺🇸US_1651,德国_0430031,🇯🇵JP-54.178.9.238-15352,🇯🇵JP-43.207.100.84-1066,🇮🇳_IN_印度_0@6,_21,未知_04302657
🚀 手动切换-2 = select,本文件创建时间：Sun Apr 30 08:32:42 UTC 2023,Relay_🇺🇸US-🇺🇸US_1650,Relay_🇺🇸US-🇺🇸US_1652,Relay_🇺🇸US-🇺🇸US_1646,美国_0430561,Relay_🇺🇸US-🇺🇸US_1649,Relay_🇺🇸US-🇺🇸US_1647,Relay_🇺🇸US-🇺🇸US_1653,🇭🇰_HK_香港_1_0@7,Relay_🇺🇸US-🇺🇸US_1648,Relay_🇦🇺AU-🇦🇺AU_23,德国_0430030,🇵🇦_PA_巴拿马_24@1,Relay_🇦🇺AU-🇦🇺AU_1134,Relay_🇺🇸US-🇺🇸US_1651,德国_0430031,🇯🇵JP-54.178.9.238-15352,🇯🇵JP-43.207.100.84-1066,🇮🇳_IN_印度_0@6,_21,未知_04302657
🛑 广告拦截 = select,DIRECT,REJECT
📢 ChatGPT = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,DIRECT,REJECT
📢 Bard = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,🇺🇸 美国节点,🇬🇧 英国节点,DIRECT,REJECT
Ⓜ️ NewBing = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,DIRECT,REJECT
Ⓜ️ 微软服务 = select,DIRECT,🚀 节点选择,♻️ 自动选择,♻️ IPv6,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,REJECT
🍎 苹果服务 = select,DIRECT,🚀 节点选择,♻️ 自动选择,♻️ IPv6,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,REJECT
🎮 国际游戏 = select,DIRECT,🚀 节点选择,♻️ 自动选择,♻️ IPv6,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,REJECT
🌍 国外媒体 = select,🚀 节点选择,♻️ 自动选择,♻️ IPv6,🚀 手动切换-1,🚀 手动切换-2,🎥 流媒体解锁,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,DIRECT,REJECT
🌏 国内媒体 = select,DIRECT,🚀 节点选择,♻️ 自动选择,♻️ IPv6,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,REJECT
🎯 国内网站 = select,DIRECT,🚀 节点选择,♻️ 自动选择,♻️ IPv6,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,REJECT
🐟 其他网站 = select,DIRECT,🚀 节点选择,♻️ 自动选择,♻️ IPv6,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇷🇺 俄罗斯节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇧🇷 巴西节点,🇪🇬 埃及节点,REJECT
🎥 流媒体解锁 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
👍 高级节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
📺 省流节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇨🇳 大陆节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇭🇰 香港节点 = url-test,🇭🇰_HK_香港_1_0@7,url=https://www.google.com/generate_204,interval=300
🇲🇴 澳门节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇹🇼 台湾节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇸🇬 新加坡节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇯🇵 日本节点 = url-test,🇯🇵JP-54.178.9.238-15352,🇯🇵JP-43.207.100.84-1066,url=https://www.google.com/generate_204,interval=300
🇰🇷 韩国节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇲🇾 马来西亚节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇹🇭 泰国节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇻🇳 越南节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇰🇭 柬埔寨节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇮🇩 印度尼西亚节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇵🇭 菲律宾节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇮🇳 印度节点 = url-test,🇮🇳_IN_印度_0@6,url=https://www.google.com/generate_204,interval=300
🇹🇷 土耳其节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇦🇺 澳大利亚节点 = url-test,Relay_🇦🇺AU-🇦🇺AU_23,Relay_🇦🇺AU-🇦🇺AU_1134,url=https://www.google.com/generate_204,interval=300
🇳🇿 新西兰节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇨🇦 加拿大节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇷🇺 俄罗斯节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇺🇸 美国节点 = url-test,Relay_🇺🇸US-🇺🇸US_1650,Relay_🇺🇸US-🇺🇸US_1652,Relay_🇺🇸US-🇺🇸US_1646,美国_0430561,Relay_🇺🇸US-🇺🇸US_1649,Relay_🇺🇸US-🇺🇸US_1647,Relay_🇺🇸US-🇺🇸US_1653,Relay_🇺🇸US-🇺🇸US_1648,Relay_🇺🇸US-🇺🇸US_1651,url=https://www.google.com/generate_204,interval=300
🇬🇧 英国节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇫🇷 法国节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇩🇪 德国节点 = url-test,德国_0430030,德国_0430031,url=https://www.google.com/generate_204,interval=300
🇵🇱 波兰节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇩🇰 丹麦节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇳🇴 挪威节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇸🇪 瑞典节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇫🇮 芬兰节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇮🇸 冰岛节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇨🇭 瑞士节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇬🇷 希腊节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇳🇱 荷兰节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇧🇷 巴西节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300
🇪🇬 埃及节点 = url-test,DIRECT,url=https://www.google.com/generate_204,interval=300

[Rule]
DOMAIN-SUFFIX,openai.com,📢 ChatGPT
DOMAIN-SUFFIX,challenges.cloudflare.com,📢 ChatGPT
DOMAIN-SUFFIX,ai.com,📢 ChatGPT
DOMAIN-SUFFIX,bard.google.com,📢 Bard
GEOIP,CN,🎯 国内网站,no-resolve
FINAL,🐟 其他网站

[Remote Rule]
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanAD.list,🛑 广告拦截
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanProgramAD.list,🛑 广告拦截
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Bing.list,Ⓜ️ NewBing
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Microsoft.list,Ⓜ️ 微软服务
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Apple.list,🍎 苹果服务
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Game.list,🎮 国际游戏
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ProxyMedia.list,🌍 国外媒体
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaMedia.list,🌏 国内媒体
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ProxyGFWlist.list,🚀 节点选择
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/LocalAreaNetwork.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/UnBan.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaDomain.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaCompanyIp.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaIp.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/GoogleCN.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/SteamCN.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Download.list,🎯 国内网站
https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Direct.list,🎯 国内网站

[URL Rewrite]
enable=true
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302

[Remote Rewrite]
https://raw.githubusercontent.com/thuhollow2/rule/main/Loon/AutoRewrite_Example.list,auto

[MITM]
enable=true
hostname=*.example.com,*.sample.com
skip-server-cert-verify=true

