#!MANAGED-CONFIG https://raw.githubusercontent.com/thuhollow2/myconfig/main/Surge4/surge4config.yaml interval=86400 strict=false

[General]
loglevel = notify
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,localhost,*.local,e.crashlytics.com,captive.apple.com,::ffff:0:0:0:0/1,::ffff:128:0:0:0/1
#DNS设置或根据自己网络情况进行相应设置
bypass-tun = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
dns-server = 119.29.29.29,223.5.5.5

[Proxy]
DIRECT = direct
本文件创建时间：Sun May 14 00:30:14 UTC 2023 = vmess, 255.255.255.255, 10086, username=00000000-0000-0000-0000-000000000000, tls=false, vmess-aead=true, skip-cert-verify=true, tfo=false, udp-relay=true
🇨🇳CN-112.132.215.189-50002 = vmess, 112.132.215.189, 50002, username=418048af-a293-4b99-9b0c-98ca3580dd24, tls=false, vmess-aead=false, skip-cert-verify=true, tfo=false, udp-relay=true
🇨🇳CN-123.249.101.15-19709 = vmess, 123.249.101.15, 19709, username=2f278a45-940a-46c1-c886-77f3b2d33987, tls=false, vmess-aead=true, ws=true, ws-path=/, sni=123.249.101.15, skip-cert-verify=true, tfo=false, udp-relay=true
🇫🇮FI-37.143.129.230-989 = ss, 37.143.129.230, 989, encrypt-method=aes-256-cfb, password=f8f7aCzcPKbsF8p3, tfo=false, udp-relay=true
🇯🇵JP-43.207.109.56-443 = ss, 43.207.109.56, 443, encrypt-method=aes-256-cfb, password=amazonskr05, tfo=false, udp-relay=true
🇯🇵JP-43.207.199.196-443 = ss, 43.207.199.196, 443, encrypt-method=aes-256-cfb, password=amazonskr05, tfo=false, udp-relay=true
🇰🇷KR-43.201.6.53-443 = ss, 43.201.6.53, 443, encrypt-method=aes-256-cfb, password=amazonskr05, tfo=false, udp-relay=true
🇺🇸US-142.0.141.113-53452 = vmess, 142.0.130.8, 53452, username=418048af-a293-4b99-9b0c-98ca3580dd24, tls=false, vmess-aead=false, skip-cert-verify=true, tfo=false, udp-relay=true
🇺🇸US-216.52.183.242-80 = ss, 216.52.183.242, 80, encrypt-method=aes-128-gcm, password=83XvX4Vo%*3a,obfs=http, tfo=false, udp-relay=true
🎥 流媒体解锁 = direct
👍 高级节点 = direct
📺 省流节点 = direct
🇭🇰 香港节点 = direct
🇲🇴 澳门节点 = direct
🇹🇼 台湾节点 = direct
🇸🇬 新加坡节点 = direct
🇲🇾 马来西亚节点 = direct
🇹🇭 泰国节点 = direct
🇻🇳 越南节点 = direct
🇰🇭 柬埔寨节点 = direct
🇮🇩 印度尼西亚节点 = direct
🇵🇭 菲律宾节点 = direct
🇲🇳 蒙古节点 = direct
🇮🇷 伊朗节点 = direct
🇮🇳 印度节点 = direct
🇹🇷 土耳其节点 = direct
🇮🇱 以色列节点 = direct
🇸🇦 沙特阿拉伯节点 = direct
🇦🇺 澳大利亚节点 = direct
🇳🇿 新西兰节点 = direct
🇨🇦 加拿大节点 = direct
🇲🇽 墨西哥节点 = direct
🇵🇦 巴拿马节点 = direct
🇷🇺 俄罗斯节点 = direct
🇺🇦 乌克兰节点 = direct
🇬🇧 英国节点 = direct
🇫🇷 法国节点 = direct
🇩🇪 德国节点 = direct
🇵🇱 波兰节点 = direct
🇩🇰 丹麦节点 = direct
🇳🇴 挪威节点 = direct
🇸🇪 瑞典节点 = direct
🇮🇸 冰岛节点 = direct
🇨🇿 捷克节点 = direct
🇨🇭 瑞士节点 = direct
🇬🇷 希腊节点 = direct
🇳🇱 荷兰节点 = direct
🇮🇹 意大利节点 = direct
🇱🇹 立陶宛节点 = direct
🇪🇸 西班牙节点 = direct
🇵🇹 葡萄牙节点 = direct
🇧🇷 巴西节点 = direct
🇨🇱 智利节点 = direct
🇵🇪 秘鲁节点 = direct
🇦🇷 阿根廷节点 = direct
🇪🇬 埃及节点 = direct
🇿🇦 南非节点 = direct

[Proxy Group]
🚀 节点选择 = select,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,🎥 流媒体解锁,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,DIRECT,REJECT
♻️ 自动选择 = url-test,本文件创建时间：Sun May 14 00:30:14 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-123.249.101.15-19709,🇫🇮FI-37.143.129.230-989,🇯🇵JP-43.207.109.56-443,🇯🇵JP-43.207.199.196-443,🇰🇷KR-43.201.6.53-443,🇺🇸US-142.0.141.113-53452,🇺🇸US-216.52.183.242-80,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
🚀 手动切换-1 = select,本文件创建时间：Sun May 14 00:30:14 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-123.249.101.15-19709,🇫🇮FI-37.143.129.230-989,🇯🇵JP-43.207.109.56-443,🇯🇵JP-43.207.199.196-443,🇰🇷KR-43.201.6.53-443,🇺🇸US-142.0.141.113-53452,🇺🇸US-216.52.183.242-80
🚀 手动切换-2 = select,本文件创建时间：Sun May 14 00:30:14 UTC 2023,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-123.249.101.15-19709,🇫🇮FI-37.143.129.230-989,🇯🇵JP-43.207.109.56-443,🇯🇵JP-43.207.199.196-443,🇰🇷KR-43.201.6.53-443,🇺🇸US-142.0.141.113-53452,🇺🇸US-216.52.183.242-80
🛑 广告拦截 = select,DIRECT,REJECT
📢 ChatGPT = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,DIRECT,REJECT
📢 Bard = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,🇺🇸 美国节点,🇬🇧 英国节点,DIRECT,REJECT
Ⓜ️ NewBing = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,DIRECT,REJECT
Ⓜ️ 微软服务 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🍎 苹果服务 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🎮 国际游戏 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🌍 国外媒体 = select,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,🎥 流媒体解锁,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,DIRECT,REJECT
🌏 国内媒体 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🎯 国内网站 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🐟 其他网站 = select,DIRECT,🚀 节点选择,♻️ 自动选择,🚀 手动切换-1,🚀 手动切换-2,♻️ IPv6-自动,🚀 IPv6-手动,👍 高级节点,📺 省流节点,🇨🇳 大陆节点,🇭🇰 香港节点,🇲🇴 澳门节点,🇹🇼 台湾节点,🇸🇬 新加坡节点,🇯🇵 日本节点,🇰🇷 韩国节点,🇲🇾 马来西亚节点,🇹🇭 泰国节点,🇻🇳 越南节点,🇰🇭 柬埔寨节点,🇮🇩 印度尼西亚节点,🇵🇭 菲律宾节点,🇲🇳 蒙古节点,🇮🇷 伊朗节点,🇮🇳 印度节点,🇹🇷 土耳其节点,🇮🇱 以色列节点,🇸🇦 沙特阿拉伯节点,🇦🇺 澳大利亚节点,🇳🇿 新西兰节点,🇨🇦 加拿大节点,🇲🇽 墨西哥节点,🇵🇦 巴拿马节点,🇷🇺 俄罗斯节点,🇺🇦 乌克兰节点,🇺🇸 美国节点,🇬🇧 英国节点,🇫🇷 法国节点,🇩🇪 德国节点,🇵🇱 波兰节点,🇩🇰 丹麦节点,🇳🇴 挪威节点,🇸🇪 瑞典节点,🇫🇮 芬兰节点,🇮🇸 冰岛节点,🇨🇿 捷克节点,🇨🇭 瑞士节点,🇬🇷 希腊节点,🇳🇱 荷兰节点,🇮🇹 意大利节点,🇱🇹 立陶宛节点,🇪🇸 西班牙节点,🇵🇹 葡萄牙节点,🇧🇷 巴西节点,🇨🇱 智利节点,🇵🇪 秘鲁节点,🇦🇷 阿根廷节点,🇪🇬 埃及节点,🇿🇦 南非节点,REJECT
🇨🇳 大陆节点 = url-test,🇨🇳CN-112.132.215.189-50002,🇨🇳CN-123.249.101.15-19709,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
🇯🇵 日本节点 = url-test,🇯🇵JP-43.207.109.56-443,🇯🇵JP-43.207.199.196-443,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
🇰🇷 韩国节点 = url-test,🇰🇷KR-43.201.6.53-443,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
🇺🇸 美国节点 = url-test,🇺🇸US-142.0.141.113-53452,🇺🇸US-216.52.183.242-80,url=http://www.gstatic.com/generate_204,interval=300,tolerance=150
🇫🇮 芬兰节点 = url-test,🇫🇮FI-37.143.129.230-989,url=http://www.gstatic.com/generate_204,interval=300,tolerance=150

[Rule]
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanAD.list,🛑 广告拦截,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/BanProgramAD.list,🛑 广告拦截,update-interval=86400
DOMAIN-SUFFIX,openai.com,📢 ChatGPT
DOMAIN-SUFFIX,challenges.cloudflare.com,📢 ChatGPT
DOMAIN-SUFFIX,ai.com,📢 ChatGPT
DOMAIN-SUFFIX,bard.google.com,📢 Bard
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Bing.list,Ⓜ️ NewBing,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Microsoft.list,Ⓜ️ 微软服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Apple.list,🍎 苹果服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Game.list,🎮 国际游戏,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ProxyMedia.list,🌍 国外媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaMedia.list,🌏 国内媒体,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ProxyGFWlist.list,🚀 节点选择,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/LocalAreaNetwork.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/UnBan.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaDomain.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaCompanyIp.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/ChinaIp.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/GoogleCN.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/SteamCN.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Download.list,🎯 国内网站,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/thuhollow2/rule/main/Clash/Direct.list,🎯 国内网站,update-interval=86400
GEOIP,CN,🎯 国内网站,no-resolve
FINAL,🐟 其他网站

